make:
	./fastcoll -p prefix -o col1 col2
	cat col1 suffix1> file1.py
	cat col2 suffix1 > file2.py
	openssl dgst -md5 file1.py file2.py




	cat file1.py suffix2> file11.py
	cat file2.py suffix2 > file21.py




GetOutput:
	python file00.py;  
	python file01.py;  
	python file02.py;  
	python file03.py;  
	python file04.py;  
	python file05.py;  
	python file06.py;  
	python file07.py;  
	python file08.py;  
	python file09.py;  
	python file010.py;  
	python file011.py;  
	python file012.py;  
	python file013.py;  
	python file014.py;  
	python file015.py;  
	python file016.py;  
	python file017.py;  
	python file018.py;  
	python file019.py;  
	python file020.py;  
	python file021.py;  
	python file022.py;  
	python file023.py;  
	python file024.py;  
	python file025.py;  
	python file026.py;  
	python file027.py;  
	python file028.py;  
	python file029.py;  
	python file030.py;  
	python file031.py;  
	python file032.py;  
	python file033.py;  
	python file034.py;  
	python file035.py;  
	python file036.py;  
	python file037.py;  
	python file038.py;  
	python file039.py;  
	python file040.py;  
	python file041.py;  
	python file042.py;  
	python file043.py;  
	python file044.py;  
	python file045.py;  
	python file046.py;  
	python file047.py;  
	python file048.py;  
	python file049.py;  
	python file050.py;  
	python file051.py;  
	python file052.py;  
	python file053.py;  
	python file054.py;  
	python file055.py;  
	python file056.py;  
	python file057.py;  
	python file058.py;  
	python file059.py;  
	python file060.py;  
	python file061.py;  
	python file062.py;  
	python file063.py;  
	
