make:
	./fastcoll -p prefix -o col1 col2
	cat col1 suffix1> file1.py
	cat col2 suffix1 > file2.py
	openssl dgst -md5 file1.py file2.py




	cat file1.py suffix2> file11.py
	cat file2.py suffix2 > file21.py




GetOutput:
	python file00.py;  
	python file01.py;  
	python file02.py;  
	python file03.py;  
	python file04.py;  
	python file05.py;  
	python file06.py;  
	python file07.py;  
	python file08.py;  
	python file09.py;  
	python file010.py;  
	python file011.py;  
	python file012.py;  
	python file013.py;  
	python file014.py;  
	python file015.py;  
	python file016.py;  
	python file017.py;  
	python file018.py;  
	python file019.py;  
	python file020.py;  
	python file021.py;  
	python file022.py;  
	python file023.py;  
	python file024.py;  
	python file025.py;  
	python file026.py;  
	python file027.py;  
	python file028.py;  
	python file029.py;  
	python file030.py;  
	python file031.py;  
	python file032.py;  
	python file033.py;  
	python file034.py;  
	python file035.py;  
	python file036.py;  
	python file037.py;  
	python file038.py;  
	python file039.py;  
	python file040.py;  
	python file041.py;  
	python file042.py;  
	python file043.py;  
	python file044.py;  
	python file045.py;  
	python file046.py;  
	python file047.py;  
	python file048.py;  
	python file049.py;  
	python file050.py;  
	python file051.py;  
	python file052.py;  
	python file053.py;  
	python file054.py;  
	python file055.py;  
	python file056.py;  
	python file057.py;  
	python file058.py;  
	python file059.py;  
	python file060.py;  
	python file061.py;  
	python file062.py;  
	python file063.py; 


md5:
	openssl dgst -md5 file00.py file01.py file02.py file03.py file04.py file05.py file06.py file07.py file08.py file09.py file010.py file011.py 		file012.py file013.py file014.py file015.py file016.py file017.py file018.py file019.py file020.py file021.py file022.py file023.py file024.py 		file025.py file026.py file027.py file028.py file029.py file030.py file031.py file032.py file033.py file034.py file035.py file036.py file037.py 		file038.py file039.py file040.py file041.py file042.py file043.py file044.py file045.py file046.py file047.py file048.py file049.py file050.py 		file051.py file052.py file053.py file054.py file055.py file056.py file057.py file058.py file059.py file060.py file061.py file062.py file063.py 
  
	
