make:
	./fastcoll -p prefix -o col1 col2
	cat col1 suffix1> file1.py
	cat col2 suffix1 > file2.py
	openssl dgst -md5 file1.py file2.py




	cat file1.py suffix2> file11.py
	cat file2.py suffix2 > file21.py
